// Main entry point for doctest test runner
// This file should be compiled exactly once with all test files

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest.h"

// The main() function is automatically generated by doctest
// Test cases from other files will be automatically discovered and run
